// ...existing code...
import {apiResponse} from "@kss-backend/core/mainframe/helpers/response";
import {adminCreateUser, adminDeleteUser} from "@kss-backend/core/mainframe/helpers/aws/cognito";
import {createAdminUserValidator} from "./validators";
import {UserModel} from "@kss-backend/core/mainframe/database/mongodb/models/user.model";
import createError from "http-errors";
import {UserRolesEnum} from "@kss-backend/core/mainframe/database/interfaces/user";

// ...academy ile ilgili kodlar kaldırıldı. createUser fonksiyonu güncellenmeli...

// ...academy ile ilgili kodlar kaldırıldı. listUsers fonksiyonu güncellenmeli...

// ...academy ile ilgili kodlar kaldırıldı. getUser fonksiyonu güncellenmeli...

// ...academy ile ilgili kodlar kaldırıldı. deleteUser fonksiyonu güncellenmeli...